config/routes.rb
Anicon::Application.routes.draw do

  # Photos
  # /photos
  resources :photos,  :only => [:index, :new, :create, :destroy, :show] do
    member do
      get :download, :upload
    end

    collection do
      get :gallery
    end
  end

  # Sessions
  # /sessions
  get 'sessions/callback', :to => 'sessions#callback', :as => 'callback'
  resources :sessions

  # Default home => as /photos
  # /
  root :to => 'photos#index'


end

app/models/photo.rb
class Photo < ActiveRecord::Base

  # Constants --------------------------------------------------------------------------------
  ALLOWED_IMAGE_CONTENT_TYPES = ['image/gif']


  # Extra additions --------------------------------------------------------------------------
  has_attached_file :photo, :styles => { :icon => '48x48#', :large => '128x128#' }


  # Associations -----------------------------------------------------------------------------
  belongs_to :user


  # Validations ------------------------------------------------------------------------------
  validates_attachment_presence :photo, :message => ': You must upload a photo.'
  validates_attachment_content_type :photo, :content_type => ALLOWED_IMAGE_CONTENT_TYPES, :message => ': It must be an animated GIF!', :if => lambda { |e| !e.photo_file_name.blank? }
  validates_attachment_size :photo, :less_than => 1.megabytes, :message => ': Your photo must be less than 1 megabyte (MB).', :if => lambda { |e| !e.photo_file_name.blank? }


  # Scopes -----------------------------------------------------------------------------------
  scope :active,      :conditions => "#{Photo::table_name}.active=1"


  # Methods ----------------------------------------------------------------------------------

  # Status
  def active?; self.active; end
  def uploaded?; self.uploaded; end

  # Actions
  def activate!; self.update_attribute(:active, true); end
  def deactivate!; self.update_attribute(:active, false); end


protected


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_filter :check_twitter_oauth, :only => [:upload]
  before_filter :get_photo, :only => [:show, :destroy, :download, :upload]

  def index
    @title = 'Resize Your Animated GIF'
    @photos = Photo.active.all(:limit => 14, :order => 'created_at desc') rescue nil unless embed?
    render :index, :layout => which_layout
  end

  def gallery
    @title = 'All Animated GIFs'
    @photos = Photo.active.all(:limit => 500, :order => 'created_at desc') rescue nil
    render :gallery, :layout => which_layout
  end

  def show
    @title = 'Your Photo'
    render :show, :layout => which_layout
  end

  def download
    #render :text => @photo.photo.path(@use_photo_size)
    send_file @photo.photo.path(@use_photo_size) and return
  end

  def upload
    if signed_in?
      client.update_profile_image(File.new(@photo.photo.path(@use_photo_size)))

      @photo.update_attributes(:uploaded => true, :user_id => current_user.id)

      flash[:notice] = {:title => 'Upload success!', :body => "Your avatar was upload. <a href='http://twitter.com/#{session[:screen_name]}' target='_blank'>Check your account &raquo;</a>".html_safe}
      redirect_to "#{photo_path(@photo)}#{embed_params}"
    else
      store_location("#{upload_photo_path(@photo)}#{embed_params}")
      initiate_oauth_connect
    end
  end

  def new
    @title = 'Upload an Animated GIF'
    @photo = Photo.new
    render :new, :layout => which_layout
  end

  def create
    @title = 'Upload an Animated GIF'
    @photo = Photo.new(params[:photo])
    @photo.active = true
    @photo.ip_address = request.remote_addr rescue nil

    if @photo.save
      flash[:notice] = {:title => 'Nice animated avatar! :D', :body => 'Now upload to Twitter or download it for your own purposes.'}
      redirect_to "#{photo_path(@photo)}#{embed_params}" and return
    else
      flash[:error] = 'Photo could not be saved.' unless embed?
      render :new, :layout => which_layout
    end
  end

  def destroy
    # if (params[:d] == 'delete' ? @photo.destroy : @photo.delete)
    #   flash[:notice] = 'Photo deleted!'
    # else
      flash[:error] = 'Could not delete photo.'
    # end

    redirect_to "#{root_path}#{embed_params}" and return
  end


protected

  def check_twitter_oauth
    redirect_back_or(root_path) unless allow_twitter_oauth?
  end

  def get_photo
    @photo = Photo.active.find(params[:id])
    raise ActiveRecord::RecordNotFound if @photo.blank?
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
- photo ||= Photo.new

- form_for photo, photos_path, :html => {:multipart => true} do |f|
  = render 'globals/error_messages', :object => photo

  - if embed?
    %input{:type => 'hidden', :name => 'embed', :value => 1}

  .c
    %fieldset.upload.left
      = f.file_field :photo
    %fieldset.buttons.left
      = f.submit 'Resize!'

  %p.note Only valid animated GIFs under 1MB are accepted.

app/views/photos/gallery.html.haml
#latest_icons
  %h2.rel
    Latest Animated GIF Uploads
    %a.button.abs{:href => "#{new_photo_path}#{embed_params}"} Upload a GIF

  #icons_grid.c
    - @photos.each do |photo|
      .left
        %a{:href => "#{photo_path(photo)}#{embed_params}"}= image_tag photo.photo.url(:icon), :title => '', :alt => '', :class => 'photo'

app/views/photos/index.html.haml
.c
  #blurb_area{:class => (!embed? ? 'left' : '')}
    %h3 Ready to Create?
    %p Get excited to make your own animated Twitter icon&hellip;
    %p.more
      %a.button{:href => "#{new_photo_path}#{embed_params}"} Start Creating!

  - if !embed? && !@photos.blank?
    #latest_icons
      %h3
        Latest Uploads
        %a.button.grey{:href => gallery_photos_path} View All
      #icons_grid.c
        - @photos.each do |photo|
          .left
            %a{:href => "#{photo_path(photo)}#{embed_params}"}= image_tag photo.photo.url(:icon), :title => '', :alt => '', :class => 'photo'

app/views/photos/new.html.haml
%h2 
  - if embed?
    Resize your animated GIF for Twitter.
  - else
    Upload your animated GIF.

- if embed? || request.post?
  = render 'photos/form', :photo => @photo

- else
  #instructions
    %h5 Instructions:
    %ol
      %li
        %p Find your imagery (or use 3fram.es to make an animated GIF).
      %li
        %p Upload your animated GIF to be resized: 
        %br
        = render 'photos/form', :photo => @photo

app/views/photos/show.html.haml
- if (embed? && @announcement.blank? && flash.blank?)
  %h2 Resized Animated GIF

- unless @photo.blank?
  .area.c
    .photo.left
      %a{:target => "_blank", :href => (@use_sendfile ? "#{download_photo_path(@photo)}#{embed_params}" : @photo.photo.url(@use_photo_size))}= image_tag(@photo.photo.url(:icon), :title => @photo.photo_file_name, :alt => @photo.photo_file_name)
    .download.left{:class => "#{(@photo.uploaded? ? 'uploaded' : '')} #{embed? ? 'embed' : ''}"}
      - unless @photo.uploaded?
        - if allow_twitter_oauth?
          %a.button{:href => "#{upload_photo_path(@photo)}#{embed_params}"} Upload to Twitter
          %br
          %span or
          %a.download{:target => "_blank", :href => (@use_sendfile ? "#{download_photo_path(@photo)}#{embed_params}" : @photo.photo.url(@use_photo_size))} download this image
        - else
          %a.button{:target => "_blank", :href => (@use_sendfile ? "#{download_photo_path(@photo)}#{embed_params}" : @photo.photo.url(@use_photo_size))} Download Image
          %br
          %span and upload to Twitter!
      - else
        %strong
          Used by
          %a{:href => "http://twitter.com/#{@photo.user.screen_name}", :target => '_blank'} @#{@photo.user.screen_name}
        %br
        %a.download{:target => "_blank", :href => (@use_sendfile ? "#{download_photo_path(@photo)}#{embed_params}" : @photo.photo.url(@use_photo_size))} download this image
      - if embed?
        %br
        %a.download{:href => "#{new_photo_path}#{embed_params}"} resize another GIF

    - unless embed?
      .again.right
        %h4 Another image?
        %p
          %a{:href => "#{new_photo_path}#{embed_params}"} Resize another animated GIF!

  - if embed?
    = render 'globals/footer'

- else
  %h1 This photo does not exist!